# API - Application Programming Interface

In [4]:
import requests
import pandas as pd

In [17]:
response = requests.get("https://api.themoviedb.org/3/movie/popular?api_key=359bd5d9715fa8c14c783d34eb70f850")

In [18]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/5h2EsPKNDdB3MAtOk9MB9Ycg9Rz.jpg',
  'genre_ids': [16, 35, 12, 10751, 9648],
  'id': 1084242,
  'original_language': 'en',
  'original_title': 'Zootopia 2',
  'overview': "After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves on the twisting trail of a great mystery when Gary De'Snake arrives and turns the animal metropolis upside down. To crack the case, Judy and Nick must go undercover to unexpected new parts of town, where their growing partnership is tested like never before.",
  'popularity': 376.1868,
  'poster_path': '/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg',
  'release_date': '2025-11-26',
  'title': 'Zootopia 2',
  'video': False,
  'vote_average': 7.6,
  'vote_count': 1297},
 {'adult': False,
  'backdrop_path': '/tyjXlexbNZQ0ZT1KEJslQtBirqc.jpg',
  'genre_ids': [12, 53, 878],
  'id': 840464,
  'original_language': 'en',
  'original_title': 'Greenland 2: Migration',
  'overview': 'Having found the safety of the Greenland bunker after the comet Clarke decimated the Earth, the Garrity family must now risk everything to embark on a perilous journey across the wasteland of Europe to find a new home.',
  'popularity': 305.9816,
  'poster_path': '/dtPwBZjzqTaObjG4fKStRkBq1uu.jpg',
  'release_date': '2026-01-07',
  'title': 'Greenland 2: Migration',
  'video': False,
  'vote_average': 6.58,
  'vote_count': 143},
 {'adult': False,
  'backdrop_path': '/3F2EXWF1thX0BdrVaKvnm6mAhqh.jpg',
  'genre_ids': [28, 53, 80],
  'id': 1306368,
  'original_language': 'en',
  'original_title': 'The Rip',
  'overview': 'Trust frays when a team of Miami cops discovers millions in cash inside a run-down stash house, calling everyone — and everything — into question.',
  'popularity': 300.7556,
  'poster_path': '/p4bW2sJKAwcHuLpfoZK7Zo63osA.jpg',
  'release_date': '2026-01-13',
  'title': 'The Rip',
  'video': False,
  'vote_average': 7.051,
  'vote_count': 867},
 {'adult': False,
  'backdrop_path': '/AecGG1XVCmkk7fT10ko3FC0dLIP.jpg',
  'genre_ids': [28, 14, 53],
  'id': 1043197,
  'original_language': 'en',
  'original_title': 'Dust Bunny',
  'overview': 'Ten-year-old Aurora asks her hitman neighbor to kill the monster under her bed that she claims ate her family. To protect her, he must battle an onslaught of assassins while accepting that some monsters are real.',
  'popularity': 239.2488,
  'poster_path': '/vobigFZFvbYPf6ElYJu07P9rH8C.jpg',
  'release_date': '2025-12-11',
  'title': 'Dust Bunny',
  'video': False,
  'vote_average': 6.56,
  'vote_count': 129},
 {'adult': False,
  'backdrop_path': '/cz4vLJrmaV1zJlRYbxqtvLzeLWB.jpg',
  'genre_ids': [28, 35, 80, 9648],
  'id': 1168190,
  'original_language': 'en',
  'original_title': 'The Wrecking Crew',
  'overview': "Estranged half-brothers Jonny and James reunite after their father's mysterious death. As they search for the truth, buried secrets reveal a conspiracy threatening to tear their family apart.",
  'popularity': 267.0247,
  'poster_path': '/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg',
  'release_date': '2026-01-28',
  'title': 'The Wrecking Crew',
  'video': False,
  'vote_average': 6.2,
  'vote_count': 40},
 {'adult': False,
  'backdrop_path': '/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg',
  'genre_ids': [28, 80, 18, 53],
  'id': 1419406,
  'original_language': 'zh',
  'original_title': '捕风追影',
  'overview': 'Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.',
  'popularity': 363.8111,
  'poster_path': '/e0RU6KpdnrqFxDKlI3NOqN8nHL6.jpg',
  'release_date': '2025-08-16',
  'title': "The Shadow's Edge",
  'video': False,
  'vote_average': 7.217,
  'vote_count': 352},
 {'adult': False,
  'backdrop_path': '/xGbNoh7aWmU81oYuxJoFI07Rz5I.jpg',
  'genre_ids': [28, 53, 80],
  'id': 1326878,
  'original_language': 'en',
  'original_title': 'Strangers',
  'overview': "Seeking revenge on her abusive husband, a woman's life takes a dark turn when she meets a mysterious hitman. Drawn into a whirlwind romance, she spirals into a dangerous vigilante spree. As the body count rises, she begins to unravel the true nature of her partner and the secrets they both conceal.",
  'popularity': 258.9958,
  'poster_path': '/ohpuwSBMgP44OPduPkpOtLxh90w.jpg',
  'release_date': '2024-08-16',
  'title': 'Strangers',
  'video': False,
  'vote_average': 5.5,
  'vote_count': 24},
 {'adult': False,
  'backdrop_path': '/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg',
  'genre_ids': [28, 878, 12],
  'id': 1242898,
  'original_language': 'en',
  'original_title': 'Predator: Badlands',
  'overview': 'Cast out from his clan, a young Predator finds an unlikely ally in a damaged android and embarks on a treacherous journey in search of the ultimate adversary.',
  'popularity': 233.7913,
  'poster_path': '/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg',
  'release_date': '2025-11-05',
  'title': 'Predator: Badlands',
  'video': False,
  'vote_average': 7.753,
  'vote_count': 1703},
 {'adult': False,
  'backdrop_path': '/3Dqievkc7krcTtDE2hjRkIsEzB1.jpg',
  'genre_ids': [878, 12, 14],
  'id': 83533,
  'original_language': 'en',
  'original_title': 'Avatar: Fire and Ash',
  'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
  'popularity': 222.7451,
  'poster_path': '/5bxrxnRaxZooBAxgUVBZ13dpzC7.jpg',
  'release_date': '2025-12-17',
  'title': 'Avatar: Fire and Ash',
  'video': False,
  'vote_average': 7.302,
  'vote_count': 1643},
 {'adult': False,
  'backdrop_path': '/swxhEJsAWms6X1fDZ4HdbvYBSf9.jpg',
  'genre_ids': [12, 35, 27],
  'id': 1234731,
  'original_language': 'en',
  'original_title': 'Anaconda',
  'overview': 'A group of friends facing mid-life crises head to the rainforest with the intention of remaking their favorite movie from their youth, only to find themselves in a fight for their lives against natural disasters, giant snakes and violent criminals.',
  'popularity': 238.1653,
  'poster_path': '/qxMv3HwAB3XPuwNLMhVRg795Ktp.jpg',
  'release_date': '2025-12-24',
  'title': 'Anaconda',
  'video': False,
  'vote_average': 5.983,
  'vote_count': 230},
 {'adult': False,
  'backdrop_path': '/gbjK8p5S1aLXWCwOoXqr9aWZvqG.jpg',
  'genre_ids': [16, 10751, 35, 12, 14],
  'id': 991494,
  'original_language': 'en',
  'original_title': 'The SpongeBob Movie: Search for SquarePants',
  'overview': 'Desperate to be a big guy, SpongeBob sets out to prove his bravery to Mr. Krabs by following The Flying Dutchman – a mysterious swashbuckling ghost pirate – on a seafaring adventure that takes him to the deepest depths of the deep sea, where no Sponge has gone before.',
  'popularity': 167.3536,
  'poster_path': '/pDWYW9v8fmJdA7N0I1MOdQA3ETq.jpg',
  'release_date': '2025-12-16',
  'title': 'The SpongeBob Movie: Search for SquarePants',
  'video': False,
  'vote_average': 6.618,
  'vote_count': 140},
 {'adult': False,
  'backdrop_path': '/sK3z0Naed3H1Wuh7a21YRVMxYqt.jpg',
  'genre_ids': [9648, 53],
  'id': 1368166,
  'original_language': 'en',
  'original_title': 'The Housemaid',
  'overview': 'Trying to escape her past, Millie Calloway accepts a job as a live-in housemaid for the wealthy Nina and Andrew Winchester. But what begins as a dream job quickly unravels into something far more dangerous—a sexy, seductive game of secrets, scandal, and power.',
  'popularity': 147.963,
  'poster_path': '/cWsBscZzwu5brg9YjNkGewRUvJX.jpg',
  'release_date': '2025-12-18',
  'title': 'The Housemaid',
  'video': False,
  'vote_average': 7.1,
  'vote_count': 551},
 {'adult': False,
  'backdrop_path': '/gQimJqYMKCkwHIo8wwYKhmnCfBr.jpg',
  'genre_ids': [28, 80, 53],
  'id': 1242501,
  'original_language': 'en',
  'original_title': 'Icefall',
  'overview': 'A young Indigenous game warden arrests an infamous poacher only to discover that the poacher knows the location of a plane carrying millions of dollars that has crashed in a frozen lake. When a group of criminals and dirty cops are alerted to the poacher’s whereabouts, the warden and the poacher team up to fight back and escape across the treacherous lake before the ice melts.',
  'popularity': 133.0881,
  'poster_path': '/5Byv6nznAb2Izd0gHpODOXnuSbo.jpg',
  'release_date': '2025-10-16',
  'title': 'Icefall',
  'video': False,
  'vote_average': 6.471,
  'vote_count': 105},
 {'adult': False,
  'backdrop_path': '/ykigHs1OIyqqV04zfFqIlSHp546.jpg',
  'genre_ids': [53, 27, 28, 9648, 878],
  'id': 1412598,
  'original_language': 'en',
  'original_title': 'Killer Whale',
  'overview': 'Follows best friends Maddie and Trish as they find themselves trapped in a remote lagoon with the dangerous killer whale named Ceto.',
  'popularity': 119.4486,
  'poster_path': '/cqbXxAw9sUr4tJ5ffEwtnz6IL9o.jpg',
  'release_date': '2026-01-16',
  'title': 'Killer Whale',
  'video': False,
  'vote_average': 5.693,
  'vote_count': 44},
 {'adult': False,
  'backdrop_path': '/iZLqwEwUViJdSkGVjePGhxYzbDb.jpg',
  'genre_ids': [878, 53],
  'id': 755898,
  'original_language': 'en',
  'original_title': 'War of the Worlds',
  'overview': 'Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.',
  'popularity': 122.9424,
  'poster_path': '/yvirUYrva23IudARHn3mMGVxWqM.jpg',
  'release_date': '2025-07-29',
  'title': 'War of the Worlds',
  'video': False,
  'vote_average': 4.213,
  'vote_count': 867},
 {'adult': False,
  'backdrop_path': '/vMxOmgmBGegjVObjlb8ugsjGgkD.jpg',
  'genre_ids': [10752, 28, 18],
  'id': 1252037,
  'original_language': 'de',
  'original_title': 'Der Tiger',
  'overview': "A German Tiger tank crew is sent on a dangerous mission to rescue the missing officer Paul von Hardenburg from a top-secret bunker behind enemy lines. As they make their way through the lethal no-man's land, they must confront not only the enemy, but also their own fears and inner demons. Fueled by the Wehrmacht's methamphetamine, their mission increasingly becomes a journey into the heart of darkness.",
  'popularity': 109.5764,
  'poster_path': '/65Jr1JAgWlu9em8zHhAfrNJJQBt.jpg',
  'release_date': '2025-09-18',
  'title': 'The Tank',
  'video': False,
  'vote_average': 6.988,
  'vote_count': 288},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 101.9656,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'video': False,
  'vote_average': 7.675,
  'vote_count': 684},
 {'adult': False,
  'backdrop_path': '/7dQTILcUKw8chDiLj8TgPXxRuED.jpg',
  'genre_ids': [27, 28, 53],
  'id': 1233413,
  'original_language': 'en',
  'original_title': 'Sinners',
  'overview': 'Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.',
  'popularity': 100.3101,
  'poster_path': '/qTvFWCGeGXgBRaINLY1zqgTPSpn.jpg',
  'release_date': '2025-04-16',
  'title': 'Sinners',
  'video': False,
  'vote_average': 7.488,
  'vote_count': 3437},
 {'adult': False,
  'backdrop_path': '/uiSaYXR0jLLWma0EPA1tcBhX6wT.jpg',
  'genre_ids': [53, 18],
  'id': 1608982,
  'original_language': 'ar',
  'original_title': 'جرس إنذار: الحفرة',
  'overview': 'Trapped in an underground pit during a storm, three students from an all-girls school must confront their personal conflicts as they fight to survive.',
  'popularity': 89.6567,
  'poster_path': '/iwZIR8wp1lqj69zsbWmZKhXTTIU.jpg',
  'release_date': '2026-01-21',
  'title': 'From the Ashes: The Pit',
  'video': False,
  'vote_average': 3.8,
  'vote_count': 15},
 {'adult': False,
  'backdrop_path': '/d10VuEOMroY7ngQi2FUhJH72k0e.jpg',
  'genre_ids': [16, 10751, 18],
  'id': 1167307,
  'original_language': 'en',
  'original_title': 'David',
  'overview': 'From the songs of his mother’s heart to the whispers of a faithful God, David’s story begins in quiet devotion. When the giant Goliath rises to terrorize a nation, a young shepherd armed with only a sling, a few stones, and unshakable faith steps forward. Pursued by power and driven by purpose, his journey tests the limits of loyalty, love, and courage—culminating in a battle not just for a crown, but for the soul of a kingdom.',
  'popularity': 95.0521,
  'poster_path': '/7lFG1WrCwAxBfyGK8ahlBVzXno7.jpg',
  'release_date': '2025-12-14',
  'title': 'David',
  'video': False,
  'vote_average': 7.9,
  'vote_count': 34}]

In [19]:
#particular colunms
pd.DataFrame(response.json()['results']).head(200)[['id', 'title', 'overview', 'popularity', 'vote_average', 'vote_count']]

,id,title,overview,popularity,vote_average,vote_count
0,1084242,Zootopia 2,After cracking the biggest case in Zootopia's ...,376.1868,7.600,1297
1,840464,Greenland 2: Migration,Having found the safety of the Greenland bunke...,305.9816,6.580,143
2,1306368,The Rip,Trust frays when a team of Miami cops discover...,300.7556,7.051,867
3,1043197,Dust Bunny,Ten-year-old Aurora asks her hitman neighbor t...,239.2488,6.560,129
4,1168190,The Wrecking Crew,Estranged half-brothers Jonny and James reunit...,267.0247,6.200,40
5,1419406,The Shadow's Edge,Macau Police brings the tracking expert police...,363.8111,7.217,352
6,1326878,Strangers,"Seeking revenge on her abusive husband, a woma...",258.9958,5.500,24
7,1242898,Predator: Badlands,"Cast out from his clan, a young Predator finds...",233.7913,7.753,1703
8,83533,Avatar: Fire and Ash,In the wake of the devastating war against the...,222.7451,7.302,1643
9,1234731,Anaconda,A group of friends facing mid-life crises head...,238.1653,5.983,230
10,991494,The SpongeBob Movie: Search for SquarePants,"Desperate to be a big guy, SpongeBob sets out ...",167.3536,6.618,140
11,1368166,The Housemaid,"Trying to escape her past, Millie Calloway acc...",147.9630,7.100,551
12,1242501,Icefall,A young Indigenous game warden arrests an infa...,133.0881,6.471,105
13,1412598,Killer Whale,Follows best friends Maddie and Trish as they ...,119.4486,5.693,44
14,755898,War of the Worlds,Will Radford is a top analyst for Homeland Sec...,122.9424,4.213,867
15,1252037,The Tank,A German Tiger tank crew is sent on a dangerou...,109.5764,6.988,288
16,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,101.9656,7.675,684
17,1233413,Sinners,"Trying to leave their troubled lives behind, t...",100.3101,7.488,3437
18,1608982,From the Ashes: The Pit,"Trapped in an underground pit during a storm, ...",89.6567,3.800,15
19,1167307,David,From the songs of his mother’s heart to the wh...,95.0521,7.900,34

In [20]:
# all columns
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/5h2EsPKNDdB3MAtOk9MB9Ycg9Rz.jpg,"[16, 35, 12, 10751, 9648]",1084242,en,Zootopia 2,After cracking the biggest case in Zootopia's ...,376.1868,/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg,2025-11-26,Zootopia 2,False,7.600,1297
1,False,/tyjXlexbNZQ0ZT1KEJslQtBirqc.jpg,"[12, 53, 878]",840464,en,Greenland 2: Migration,Having found the safety of the Greenland bunke...,305.9816,/dtPwBZjzqTaObjG4fKStRkBq1uu.jpg,2026-01-07,Greenland 2: Migration,False,6.580,143
2,False,/3F2EXWF1thX0BdrVaKvnm6mAhqh.jpg,"[28, 53, 80]",1306368,en,The Rip,Trust frays when a team of Miami cops discover...,300.7556,/p4bW2sJKAwcHuLpfoZK7Zo63osA.jpg,2026-01-13,The Rip,False,7.051,867
3,False,/AecGG1XVCmkk7fT10ko3FC0dLIP.jpg,"[28, 14, 53]",1043197,en,Dust Bunny,Ten-year-old Aurora asks her hitman neighbor t...,239.2488,/vobigFZFvbYPf6ElYJu07P9rH8C.jpg,2025-12-11,Dust Bunny,False,6.560,129
4,False,/cz4vLJrmaV1zJlRYbxqtvLzeLWB.jpg,"[28, 35, 80, 9648]",1168190,en,The Wrecking Crew,Estranged half-brothers Jonny and James reunit...,267.0247,/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg,2026-01-28,The Wrecking Crew,False,6.200,40
5,False,/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg,"[28, 80, 18, 53]",1419406,zh,捕风追影,Macau Police brings the tracking expert police...,363.8111,/e0RU6KpdnrqFxDKlI3NOqN8nHL6.jpg,2025-08-16,The Shadow's Edge,False,7.217,352
6,False,/xGbNoh7aWmU81oYuxJoFI07Rz5I.jpg,"[28, 53, 80]",1326878,en,Strangers,"Seeking revenge on her abusive husband, a woma...",258.9958,/ohpuwSBMgP44OPduPkpOtLxh90w.jpg,2024-08-16,Strangers,False,5.500,24
7,False,/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg,"[28, 878, 12]",1242898,en,Predator: Badlands,"Cast out from his clan, a young Predator finds...",233.7913,/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg,2025-11-05,Predator: Badlands,False,7.753,1703
8,False,/3Dqievkc7krcTtDE2hjRkIsEzB1.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,222.7451,/5bxrxnRaxZooBAxgUVBZ13dpzC7.jpg,2025-12-17,Avatar: Fire and Ash,False,7.302,1643
9,False,/swxhEJsAWms6X1fDZ4HdbvYBSf9.jpg,"[12, 35, 27]",1234731,en,Anaconda,A group of friends facing mid-life crises head...,238.1653,/qxMv3HwAB3XPuwNLMhVRg795Ktp.jpg,2025-12-24,Anaconda,False,5.983,230
10,False,/gbjK8p5S1aLXWCwOoXqr9aWZvqG.jpg,"[16, 10751, 35, 12, 14]",991494,en,The SpongeBob Movie: Search for SquarePants,"Desperate to be a big guy, SpongeBob sets out ...",167.3536,/pDWYW9v8fmJdA7N0I1MOdQA3ETq.jpg,2025-12-16,The SpongeBob Movie: Search for SquarePants,False,6.618,140
11,False,/sK3z0Naed3H1Wuh7a21YRVMxYqt.jpg,"[9648, 53]",1368166,en,The Housemaid,"Trying to escape her past, Millie Calloway acc...",147.9630,/cWsBscZzwu5brg9YjNkGewRUvJX.jpg,2025-12-18,The Housemaid,False,7.100,551
12,False,/gQimJqYMKCkwHIo8wwYKhmnCfBr.jpg,"[28, 80, 53]",1242501,en,Icefall,A young Indigenous game warden arrests an infa...,133.0881,/5Byv6nznAb2Izd0gHpODOXnuSbo.jpg,2025-10-16,Icefall,False,6.471,105
13,False,/ykigHs1OIyqqV04zfFqIlSHp546.jpg,"[53, 27, 28, 9648, 878]",1412598,en,Killer Whale,Follows best friends Maddie and Trish as they ...,119.4486,/cqbXxAw9sUr4tJ5ffEwtnz6IL9o.jpg,2026-01-16,Killer Whale,False,5.693,44
14,False,/iZLqwEwUViJdSkGVjePGhxYzbDb.jpg,"[878, 53]",755898,en,War of the Worlds,Will Radford is a top analyst for Homeland Sec...,122.9424,/yvirUYrva23IudARHn3mMGVxWqM.jpg,2025-07-29,War of the Worlds,False,4.213,867
15,False,/vMxOmgmBGegjVObjlb8ugsjGgkD.jpg,"[10752, 28, 18]",1252037,de,Der Tiger,A German Tiger tank crew is sent on a dangerou...,109.5764,/65Jr1JAgWlu9em8zHhAfrNJJQBt.jpg,2025-09-18,The Tank,False,6.988,288
16,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,101.9656,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,Demon Slayer: Kimetsu no Yaiba Infinity Castle,False,7.675,684
17,False,/7dQTILcUKw8chDiLj8TgPXxRuED.jpg,"[27, 28, 53]",1233413,en,Sinners,"Trying to leave their troubled lives behind, t...",100.3101,/qTvFWCGeGXgBRaINLY1zqgTPSpn.jpg,2025-04-16,Sinners,False,7.488,3437
18,False,/uiSaYXR0jLLWma0EPA1tcBhX6wT.jpg,"[53, 18]",1608982,ar,جرس إنذار: الحفرة,"Trapped in an underground pit during a storm, ...",89.6567,/iwZIR8wp1lqj69zsbWmZKhXTTIU.jpg,2026-01-21,From the Ashes: The Pit,False,3.800,15
19,False,/d10VuEOMroY7ngQi2FUhJH72k0e.jpg,"[16, 10751, 18]",1167307,en,David,From the songs of his mother’s heart to the wh...,95.0521,/7lFG1WrCwAxBfyGK8ahlBVzXno7.jpg,2025-12-14,David,False,7.900,34

In [21]:
df = pd.DataFrame()

In [22]:
df

Empty DataFrame
Columns: []
Index: []

for i in range(1, 555):
    responserequests.get("https://api.themoviedb.org/3/movie/popularapi_key=359bd5d9715fa8c14c783d34eb70f850")
    temp_df = pd.DataFra

In [29]:
for i in range(1,5):
    response = requests.get("https://api.themoviedb.org/3/movie/popular?api_key=359bd5d9715fa8c14c783d34eb70f850&page={i}")
    temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'popularity', 'vote_average', 'vote_count']]
    df.concat(df , temp_df, ignore_index= True)

KeyError: 'results'