In [1]:
!pip install prettytable
from prettytable import PrettyTable
table= PrettyTable()
table.field_names = ["S.No.","Name","Description","Deadline","Priority"]
table.add_row(["1","Exam","Completed","14/08/2025","Higher"])
table.add_row(["2","Data Science","Progress","15/01/2026","Higher"])
table.add_row(["3","Exam","Completed","14/08/2025","Higher"])
table.add_row(["4","Exam","Completed","14/08/2025","Higher"])


print(table)

Requirement already satisfied: prettytable in c:\users\jiyad\appdata\local\programs\python\python313\lib\site-packages (3.16.0)
Requirement already satisfied: wcwidth in c:\users\jiyad\appdata\local\programs\python\python313\lib\site-packages (from prettytable) (0.2.13)
+-------+--------------+-------------+------------+----------+
| S.No. |     Name     | Description |  Deadline  | Priority |
+-------+--------------+-------------+------------+----------+
|   1   |     Exam     |  Completed  | 14/08/2025 |  Higher  |
|   2   | Data Science |   Progress  | 15/01/2026 |  Higher  |
|   3   |     Exam     |  Completed  | 14/08/2025 |  Higher  |
|   4   |     Exam     |  Completed  | 14/08/2025 |  Higher  |
+-------+--------------+-------------+------------+----------+

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
from prettytable import PrettyTable

# Create table object
table = PrettyTable()

# Add column headings
table.field_names = ["Name", "Age", "City"]

# Add rows (data)
table.add_row(["Jiya", 21, "Bhopal"])
table.add_row(["Amit", 25, "Delhi"])
table.add_row(["Priya", 22, "Mumbai"])

# Print the table
print(table)

+-------+-----+--------+
|  Name | Age |  City  |
+-------+-----+--------+
|  Jiya |  21 | Bhopal |
|  Amit |  25 | Delhi  |
| Priya |  22 | Mumbai |
+-------+-----+--------+

In [8]:
# Install PrettyTable (only run this once)
!pip install prettytable

# Import PrettyTable and display
from prettytable import PrettyTable
from IPython.display import display, Markdown

# Create table object
table = PrettyTable()

# Add column headings
table.field_names = ["Name", "Age", "City"]

# Add rows (data)
table.add_row(["Jiya", 21, "Bhopal"])
table.add_row(["Amit", 25, "Delhi"])
table.add_row(["Priya", 22, "Mumbai"])

# Display in Jupyter
display(Markdown(f"```\n{table}\n```"))

Requirement already satisfied: prettytable in c:\users\jiyad\appdata\local\programs\python\python313\lib\site-packages (3.16.0)
Requirement already satisfied: wcwidth in c:\users\jiyad\appdata\local\programs\python\python313\lib\site-packages (from prettytable) (0.2.13)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

```
+-------+-----+--------+
|  Name | Age |  City  |
+-------+-----+--------+
|  Jiya |  21 | Bhopal |
|  Amit |  25 | Delhi  |
| Priya |  22 | Mumbai |
+-------+-----+--------+
```

In [ ]:
### task 1 to do list
print("---------------====To Do List====-----------------")
print("----------------------------------------------------")
print("S.No.  Work      Description   Deadline   priority")
print("----------------------------------------------------")
one= [  1 ,  "Exam ", " Completed ","  15/08/2025  "," Higher"]
print(end="")
two= [  2  , "Data"  , "Progress"   ," 15/01/2026 ", "Higher"]
third=[ 3   ,"DSA "  , "Pending " ,  "01/08/2026   ","Medium"]
four= [ 4  , "Wander", "Pending "   ,"31/08/2025   ","ower "]
print(one)
print(two)
print(third)
print(four)
print("----------------------------------------------------")
update=(input("If you Want to Update enter yes or no :"))
if update=="yes":
    num=int(input("Enter number"))
elif update=="no":
    print("thankq😊")
if update=="yes":
    print("WHAT YOU WANT TO UPDATE")
    print("1. Work")
    print("2. Discription")
    print("3. Deadline")
    print("4. priority")
    
# for update 
    select=int(input("Enter Number"))
if num==1:
    if select==1:
        one.pop(1)
        name=(input("write that you want to update :"))
        one.insert(1,name)
        print(one)   
    elif select==2:
        one.pop(2)
        name=(input("write that you want to update :"))
        one.insert(2,name)
        print(one)
    elif select==3:
        one.pop(3)
        name=(input("write that you want to update :"))
        one.insert(3,name)
        print(one)
    elif select==4:
        one.pop(4)
        name=(input("write that you want to update :"))
        one.insert(4,name)
        print(one)
    
elif num==2:
    if select==1:
        two.pop(1)
        name=(input("write that you want to update :"))
        two.insert(1,name)
        print(two)
    elif select==2:
        two.pop(2)
        name=(input("write that you want to update :"))
        two.insert(2,name)
        print(two)
    elif select==3:
        two.pop(3)
        name=(input("write that you want to update :"))
        two.insert(3,name)
        print(two)
    elif select==4:
        two.pop(4)
        name=(input("write that you want to update :"))
        two.insert(4,name)
        print(two)
elif num==3:
    if select==1:
        third.pop(1)
        name=(input("write that you want to update :"))
        third.insert(1,name)
        print(third)
    elif select==2:
        third.pop(2)
        name=(input("write that you want to update :"))
        third.insert(2,name)
        print(third)
    elif select==3:
        third.pop(3)
        name=(input("write that you want to update :"))
        third.insert(3,name)
        print(third)
    elif third==4:
        two.pop(4)
        name=(input("write that you want to update :"))
        third.insert(4,name)
        print(third)
elif num==4:
    if select==1:
        four.pop(1)
        name=(input("write that you want to update :"))
        four.insert(1,name)
        print(four)
    elif select==2:
        four.pop(2)
        name=(input("write that you want to update :"))
        four.insert(2,name)
        print(four)
    elif select==3:
        four.pop(3)
        name=(input("write that you want to update :"))
        four.insert(3,name)
        print(four)
    elif select==4:
        four.pop(4)
        name=(input("write that you want to update :"))
        four.insert(4,name)
        print(four)
print(one)
print(two)
print(third)
print(four)

---------------====To Do List====-----------------
----------------------------------------------------
S.No.  Work      Description   Deadline   priority
----------------------------------------------------
[1, 'Exam ', ' Completed ', '  15/08/2025  ', ' Higher']
[2, 'Data', 'Progress', ' 15/01/2026 ', 'Higher']
[3, 'DSA ', 'Pending ', '01/08/2026   ', 'Medium']
[4, 'Wander', 'Pending ', '31/08/2025   ', 'ower ']
----------------------------------------------------

If you Want to Update enter yes or no : yes

In [ ]:
update=int(input("If you Want to Update so Enter Number"))

In [ ]:
elif select==2:
    one.pop(1)
    name=(input("write what you want to update"))
    one.insert(1,name)
    print(two)
elif select==3:
    one.pop(1)
    name=(input("write what you want to update"))
    one.insert(1,name)
    print(third)
elif select==4:
    one.pop(1)
    name=(input("write what you want to update"))
    one.insert(1,name)
    print(four)

In [ ]:
# task 1 to do list
print("---------------====To Do List====-----------------")
print("----------------------------------------------------")
print("S.No.  Work      Description   Deadline   priority")
print("----------------------------------------------------")
one= [  1 ,  "Exam ", " Completed ","  15/08/2025  "," Higher"]
print(end="")
two= [  2  , "Data"  , "Progress"   ," 15/01/2026 ", "Higher"]
third=[ 3   ,"DSA "  , "Pending " ,  "01/08/2026   ","Medium"]
four= [ 4  , "Wander", "Pending "   ,"31/08/2025   ","ower "]
print(one)
print(two)
print(third)
print(four)
print("----------------------------------------------------")
update=(input("If you Want to Update enter yes or no :"))
if update=="yes":
    num=int(input("Enter number"))
elif update=="no":
    print("thankq😊")
if update=="yes":
    print("WHAT YOU WANT TO UPDATE")
    print("1. Work")
    print("2. Discription")
    print("3. Deadline")
    print("4. priority")
select=int(input("select what you want to update"))
for i in range(4):
    if num==i:
        select=int(input("select what you want to update"))
        for i in range(4):
            if select==j:

In [7]:
import pandas as pd

In [8]:

data={
    'Work' : ["Exam","Data Science","wander","Competition"],
    'Description':["Completed","pending","pending",'Progress'],
    'Deadline':['15/08/2025','16/01/2026','15/09/2025','30/04/2026'],
    'priority':['Higher','Medium','Lower','Higher']
}

In [11]:
todo=pd.DataFrame(data)
todo

           Work Description    Deadline priority
0          Exam   Completed  15/08/2025   Higher
1  Data Science     pending  16/01/2026   Medium
2        wander     pending  15/09/2025    Lower
3   Competition    Progress  30/04/2026   Higher

In [12]:
todo.index=[1,2,3,4]

In [13]:
todo

           Work Description    Deadline priority
1          Exam   Completed  15/08/2025   Higher
2  Data Science     pending  16/01/2026   Medium
3        wander     pending  15/09/2025    Lower
4   Competition    Progress  30/04/2026   Higher

In [39]:
update=input("For Undate Print yes or no : ")
if update=="yes":
    print(todo.columns)
    ch=input('choose :')
    for j in range(1,5):
        if todo.columns[j]==ch:
            no=input("num 1,2,3,4")
            for j in range(1,5):
                if no==j:
                    final=input('write what you want to update :')
                    todo[j][work]=final

For Undate Print yes or no :  yes

Index(['Work', 'Description', 'Deadline', 'priority'], dtype='object')

choose : work

IndexError: index 4 is out of bounds for axis 0 with size 4

In [19]:
todo.columns[0]

'Work'

In [ ]:
todo.columns

In [ ]:
todo.columns