In [1]:
import pandas as pd

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\jiyad\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\jiyad\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install --upgrade pip

Requirement already satisfied: pip in c:\users\jiyad\anaconda3\lib\site-packages (25.1)
Collecting pip
  Using cached pip-25.2-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-25.2-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.1
    Uninstalling pip-25.1:
      Successfully uninstalled pip-25.1
Successfully installed pip-25.2
Note: you may need to restart the kernel to use updated packages.

In [24]:
df={
    'name': ['jiya', 'sandhya', 'aaditya', 'jeet'],
 'age': [18, 19, 20, 19],
 'height': [5.3, 5.4, 5.8, 5.5]
}
df

{'name': ['jiya', 'sandhya', 'aaditya', 'jeet'],
 'age': [18, 19, 20, 19],
 'height': [5.3, 5.4, 5.8, 5.5]}

In [5]:
print(pd.DataFrame(df))

      name  age  height
0     jiya   18     5.3
1  sandhya   19     5.4
2  aaditya   20     5.8
3     jeet   19     5.5

In [6]:
import pandas as pd
a=pd.read_csv("C:\\Users\\jiyad\\OneDrive\\Desktop\\jiya.csv")
a

   Train No.  Sheet NO.    City
0    4663364         75  indore
1      64356         66   delhi
2       7654         76    kota
3    7476757         86  kaneda

In [7]:
fruit=pd.read_csv("C:\\Users\\jiyad\\OneDrive\\Desktop\\fruit1.csv")
fruit

,FRUIT,MONTH,SALES,SALESMAN,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Banana,January,34,BOB,NaN,NaN,NaN,BOB,NaN,NaN,Banana,NaN
1,Apple,February,45,DOT,NaN,NaN,NaN,DOT,NaN,NaN,Apple,NaN
2,Pear,March,2000,SUE,NaN,NaN,NaN,SUE,NaN,NaN,Pear,NaN
3,Kiwi,April,76,MARY,NaN,NaN,NaN,NaN,NaN,NaN,Kiwi,NaN
4,Strawberry,May,87,DOT,NaN,NaN,NaN,January,NaN,NaN,Strawberry,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
289,Strawberry,February,4,DOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,Banana,March,8,SUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,Apple,April,6,ALICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,Pear,May,9,DOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,Kiwi,June,76,SUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
panda=pd.read_csv("C:\\Users\\jiyad\\OneDrive\\Desktop\\fruit1.csv")
panda

,FRUIT,MONTH,SALES,SALESMAN,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Banana,January,34,BOB,NaN,NaN,NaN,BOB,NaN,NaN,Banana,NaN
1,Apple,February,45,DOT,NaN,NaN,NaN,DOT,NaN,NaN,Apple,NaN
2,Pear,March,2000,SUE,NaN,NaN,NaN,SUE,NaN,NaN,Pear,NaN
3,Kiwi,April,76,MARY,NaN,NaN,NaN,NaN,NaN,NaN,Kiwi,NaN
4,Strawberry,May,87,DOT,NaN,NaN,NaN,January,NaN,NaN,Strawberry,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
289,Strawberry,February,4,DOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,Banana,March,8,SUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,Apple,April,6,ALICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,Pear,May,9,DOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,Kiwi,June,76,SUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#by default give 5 rows
panda.head()

,FRUIT,MONTH,SALES,SALESMAN,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Banana,January,34,BOB,NaN,NaN,NaN,BOB,NaN,NaN,Banana,NaN
1,Apple,February,45,DOT,NaN,NaN,NaN,DOT,NaN,NaN,Apple,NaN
2,Pear,March,2000,SUE,NaN,NaN,NaN,SUE,NaN,NaN,Pear,NaN
3,Kiwi,April,76,MARY,NaN,NaN,NaN,NaN,NaN,NaN,Kiwi,NaN
4,Strawberry,May,87,DOT,NaN,NaN,NaN,January,NaN,NaN,Strawberry,NaN

In [10]:
#by default give 5 rows
panda.tail()

,FRUIT,MONTH,SALES,SALESMAN,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
289,Strawberry,February,4,DOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,Banana,March,8,SUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,Apple,April,6,ALICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,Pear,May,9,DOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,Kiwi,June,76,SUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
fruit.describe()

,SALES,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 9,Unnamed: 11
count,294.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,45.193878,NaN,NaN,NaN,NaN,NaN,NaN
std,122.047772,NaN,NaN,NaN,NaN,NaN,NaN
min,2.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,32.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,76.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,2000.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
fruit.shape

(294, 12)

In [13]:
fruit.columns

Index(['FRUIT', 'MONTH', 'SALES', 'SALESMAN', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11'],
      dtype='object')

In [14]:
fruit.index

RangeIndex(start=0, stop=294, step=1)

In [15]:
#for print column accodingg slicing in which if name is in the form of like (friut name) is also wil do
fruit['FRUIT'][:10]

0        Banana
1         Apple
2          Pear
3          Kiwi
4    Strawberry
5        Banana
6         Apple
7          Pear
8          Kiwi
9    Strawberry
Name: FRUIT, dtype: object

In [16]:
#for print column accodingg slicing inn which if name in the form of like(fruit name )so it can do 
fruit.FRUIT[:5]

0        Banana
1         Apple
2          Pear
3          Kiwi
4    Strawberry
Name: FRUIT, dtype: object

In [17]:
#print column of one column and prinnt column from index wise
fruit.FRUIT.iloc[:7]

0        Banana
1         Apple
2          Pear
3          Kiwi
4    Strawberry
5        Banana
6         Apple
Name: FRUIT, dtype: object

In [18]:
#row  indexing for dataftame
#print multiple column
fruit.iloc[:6]  #print index wise

,FRUIT,MONTH,SALES,SALESMAN,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Banana,January,34,BOB,NaN,NaN,NaN,BOB,NaN,NaN,Banana,NaN
1,Apple,February,45,DOT,NaN,NaN,NaN,DOT,NaN,NaN,Apple,NaN
2,Pear,March,2000,SUE,NaN,NaN,NaN,SUE,NaN,NaN,Pear,NaN
3,Kiwi,April,76,MARY,NaN,NaN,NaN,NaN,NaN,NaN,Kiwi,NaN
4,Strawberry,May,87,DOT,NaN,NaN,NaN,January,NaN,NaN,Strawberry,NaN
5,Banana,June,34,SUE,NaN,NaN,NaN,February,NaN,NaN,NaN,NaN

In [19]:
#row  indexing for dataftame
#print multiple column
fruit.loc[:6]  #print without index wise

,FRUIT,MONTH,SALES,SALESMAN,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Banana,January,34,BOB,NaN,NaN,NaN,BOB,NaN,NaN,Banana,NaN
1,Apple,February,45,DOT,NaN,NaN,NaN,DOT,NaN,NaN,Apple,NaN
2,Pear,March,2000,SUE,NaN,NaN,NaN,SUE,NaN,NaN,Pear,NaN
3,Kiwi,April,76,MARY,NaN,NaN,NaN,NaN,NaN,NaN,Kiwi,NaN
4,Strawberry,May,87,DOT,NaN,NaN,NaN,January,NaN,NaN,Strawberry,NaN
5,Banana,June,34,SUE,NaN,NaN,NaN,February,NaN,NaN,NaN,NaN
6,Apple,July,56,JON,NaN,NaN,NaN,March,NaN,NaN,>25,NaN