In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("C:\\Users\\jiyad\\OneDrive\\Documents\\Desktop\\Project_2_data\\dataset_1 - dataset_1.csv")
df

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
0,1,01-01-2011,1,0,1,0,False,6,1,0.24
1,2,01-01-2011,1,0,1,1,False,6,1,0.22
2,3,01-01-2011,1,0,1,2,False,6,1,0.22
3,4,01-01-2011,1,0,1,3,False,6,1,0.24
4,5,01-01-2011,1,0,1,4,False,6,1,0.24
...,...,...,...,...,...,...,...,...,...,...
605,606,28-01-2011,1,0,1,11,False,5,3,0.18
606,607,28-01-2011,1,0,1,12,False,5,3,0.18
607,608,28-01-2011,1,0,1,13,False,5,3,0.18
608,609,28-01-2011,1,0,1,14,False,5,3,0.22
609,610,28-01-2011,1,0,1,15,False,5,2,0.20

In [6]:
df.isnull()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
605,False,False,False,False,False,False,False,False,False,False
606,False,False,False,False,False,False,False,False,False,False
607,False,False,False,False,False,False,False,False,False,False
608,False,False,False,False,False,False,False,False,False,False
609,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [31]:
# find mix data type dat
df.select_dtypes(include="object")

         dteday
0    01-01-2011
1    01-01-2011
2    01-01-2011
3    01-01-2011
4    01-01-2011
..          ...
605  28-01-2011
606  28-01-2011
607  28-01-2011
608  28-01-2011
609  28-01-2011

[610 rows x 1 columns]

In [10]:
data=pd.read_csv("C:\\Users\\jiyad\\OneDrive\\Documents\\Desktop\\Project_2_data\\dataset_2.xlsx - dataset_2.csv")
data

     Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]

In [11]:
data.isnull()

     Unnamed: 0  instant  atemp    hum  windspeed  casual  registered    cnt
0         False    False  False  False      False   False       False  False
1         False    False  False  False      False   False       False  False
2         False    False  False  False      False   False       False  False
3         False    False  False  False      False   False       False  False
4         False    False  False  False      False   False       False  False
..          ...      ...    ...    ...        ...     ...         ...    ...
605       False    False  False  False      False   False       False  False
606       False    False  False  False      False   False       False  False
607       False    False  False  False      False   False       False  False
608       False    False  False  False      False   False       False  False
609       False    False  False  False      False   False       False  False

[610 rows x 8 columns]

In [14]:
data.head(10)

   Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0           0        1  0.2879  0.81     0.0000       3          13   16
1           1        2  0.2727  0.80     0.0000       8          32   40
2           2        3  0.2727  0.80     0.0000       5          27   32
3           3        4  0.2879  0.75     0.0000       3          10   13
4           4        5  0.2879  0.75     0.0000       0           1    1
5           5        6  0.2576  0.75     0.0896       0           1    1
6           6        7  0.2727  0.80     0.0000       2           0    2
7           7        8  0.2576  0.86     0.0000       1           2    3
8           8        9     NaN  0.75     0.0000       1           7    8
9           9       10  0.3485  0.76     0.0000       8           6   14

In [12]:
# null value in partucular collumn
data.isnull().sum()

Unnamed: 0     0
instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

In [13]:
#total null value
data.isnull().sum().sum()

np.int64(11)

In [26]:
#find mode of a particular column
mode=data["atemp"].mode()[0]
print(mode)
data["atemp"].fillna(data["atemp"].mode()[0],inplace = True)

0.197

In [24]:
data.head(10)

   Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0           0        1  0.2879  0.81     0.0000       3          13   16
1           1        2  0.2727  0.80     0.0000       8          32   40
2           2        3  0.2727  0.80     0.0000       5          27   32
3           3        4  0.2879  0.75     0.0000       3          10   13
4           4        5  0.2879  0.75     0.0000       0           1    1
5           5        6  0.2576  0.75     0.0896       0           1    1
6           6        7  0.2727  0.80     0.0000       2           0    2
7           7        8  0.2576  0.86     0.0000       1           2    3
8           8        9  0.1970  0.75     0.0000       1           7    8
9           9       10  0.3485  0.76     0.0000       8           6   14

In [29]:
# finnd object type data (like string type)
data.select_dtypes(include="object")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[610 rows x 0 columns]

In [37]:
# find null value in object type data
data.select_dtypes(include="object").isnull().sum()

Series([], dtype: float64)

In [39]:
# fill mode n all object datatype null value
for i in data.select_dtypes(include="object").columns:
    data[i].fillna(df[i].mode()[0],inplace=True)
#this dataset has no object type colunms so thata why no need to fill mode

In [40]:
#find persantage of the all columns wise null value
(data.isnull().sum()/data.shape[0])*100

Unnamed: 0    0.0
instant       0.0
atemp         0.0
hum           0.0
windspeed     0.0
casual        0.0
registered    0.0
cnt           0.0
dtype: float64

In [41]:
# total dataset null value persantage
((data.isnull().sum().sum())/(data.shape[0]*data.shape[1]))*100

np.float64(0.0)