# Handel missing value

In [1]:
import pandas as pd

In [2]:
data = {
    'Name' : ['Pawan','kapil','Lalit','Ishan','Om'],
    'Age' : [25,None,44,23,None],
    'Salary' : [50000,60000, 70000, None,None]
}
df = pd.DataFrame(data)
df

    Name   Age   Salary
0  Pawan  25.0  50000.0
1  kapil   NaN  60000.0
2  Lalit  44.0  70000.0
3  Ishan  23.0      NaN
4     Om   NaN      NaN

In [3]:
# isnull().sum()
print(df.isnull().sum())

Name      0
Age       2
Salary    2
dtype: int64

In [4]:
#  total null vlaue
df.isnull().sum().sum()

np.int64(4)

In [5]:
dataF = df.copy()
dataF

    Name   Age   Salary
0  Pawan  25.0  50000.0
1  kapil   NaN  60000.0
2  Lalit  44.0  70000.0
3  Ishan  23.0      NaN
4     Om   NaN      NaN

In [6]:
df['Age'].mean()

np.float64(30.666666666666668)

In [7]:
dataF['Age'].fillna(dataF['Age'].mean(),inplace=True)
dataF

C:\Users\jiyad\AppData\Local\Temp\ipykernel_13676\2765560217.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataF['Age'].fillna(dataF['Age'].mean(),inplace=True)

    Name        Age   Salary
0  Pawan  25.000000  50000.0
1  kapil  30.666667  60000.0
2  Lalit  44.000000  70000.0
3  Ishan  23.000000      NaN
4     Om  30.666667      NaN

# Encode Categorical Values

In [8]:
data = {
    'Name': ['Aditi', 'Rohan', 'Priya', 'Arjun', 'Sneha', 'Karan', 'Neha', 'Raj'],
    'Gender': ['Female', 'Male', None, 'Male', 'Female', 'Male', 'Female', None],
    'Department': ['CSE', 'AIML', 'IT', None, 'ECE', 'IT', 'AIML', 'CSE'],
    'Age': [19, None, 18, 21, 20, None, 22, 20],
    'CGPA': [8.5, 7.8, None, 7.2, 8.8, 8.1, 9.0, None],
    'City': ['Indore', 'Bhopal', 'Ujjain', 'Indore', None, 'Pune', 'Bhopal', 'Indore']
}

In [9]:
dataset = pd.DataFrame(data)
dataset

    Name  Gender Department   Age  CGPA    City
0  Aditi  Female        CSE  19.0   8.5  Indore
1  Rohan    Male       AIML   NaN   7.8  Bhopal
2  Priya    None         IT  18.0   NaN  Ujjain
3  Arjun    Male       None  21.0   7.2  Indore
4  Sneha  Female        ECE  20.0   8.8    None
5  Karan    Male         IT   NaN   8.1    Pune
6   Neha  Female       AIML  22.0   9.0  Bhopal
7    Raj    None        CSE  20.0   NaN  Indore

In [11]:
dataset.isnull().sum()

Name          0
Gender        2
Department    1
Age           2
CGPA          2
City          1
dtype: int64

In [12]:
dataset.isnull().sum().sum()

np.int64(8)

In [13]:
dataset.select_dtypes(include = 'float64')

    Age  CGPA
0  19.0   8.5
1   NaN   7.8
2  18.0   NaN
3  21.0   7.2
4  20.0   8.8
5   NaN   8.1
6  22.0   9.0
7  20.0   NaN

In [23]:
print(dataset['Age'].mean())
print(dataset['CGPA'].mean())

20.0
8.233333333333334

In [14]:
# fill numerical nulll value by call sklearn library

In [15]:
from sklearn.impute import SimpleImputer

In [16]:
si = SimpleImputer(strategy = "mean")

In [18]:
dataset[['Age', 'CGPA']] = si.fit_transform(dataset[['Age', 'CGPA']])
dataset

    Name  Gender Department   Age      CGPA    City
0  Aditi  Female        CSE  19.0  8.500000  Indore
1  Rohan    Male       AIML  20.0  7.800000  Bhopal
2  Priya    None         IT  18.0  8.233333  Ujjain
3  Arjun    Male       None  21.0  7.200000  Indore
4  Sneha  Female        ECE  20.0  8.800000    None
5  Karan    Male         IT  20.0  8.100000    Pune
6   Neha  Female       AIML  22.0  9.000000  Bhopal
7    Raj    None        CSE  20.0  8.233333  Indore

In [24]:
# decrease moredecimal value after point in 2 value only
dataset['CGPA'] = dataset['CGPA'].round(2)

In [25]:
dataset

    Name  Gender Department   Age  CGPA    City
0  Aditi  Female        CSE  19.0  8.50  Indore
1  Rohan    Male       AIML  20.0  7.80  Bhopal
2  Priya    None         IT  18.0  8.23  Ujjain
3  Arjun    Male       None  21.0  7.20  Indore
4  Sneha  Female        ECE  20.0  8.80    None
5  Karan    Male         IT  20.0  8.10    Pune
6   Neha  Female       AIML  22.0  9.00  Bhopal
7    Raj    None        CSE  20.0  8.23  Indore

# fill catagorical data

In [1]:
from sklearn.preprocessing import LabelEncoder