In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read CSV File

In [2]:
# data set
data =  pd.read_csv("C:\\Datasets_ml\\StudentPerformanceFactors.csv")
df = pd.DataFrame(data)
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [3]:
df.shape

(6607, 20)

# Handle Missing Data

In [4]:
#dropna drop all rows which has null values
df = df.dropna()

In [5]:
df = df.drop(columns = ['Parental_Involvement', 'Access_to_Resources', 'Family_Income', 'Peer_Influence','Physical_Activity', 'Parental_Education_Level',"Distance_from_Home","Teacher_Quality","Learning_Disabilities"])

In [6]:
df.dropna()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,School_Type,Gender,Exam_Score
0,23,84,No,7,73,Low,Yes,0,Public,Male,67
1,19,64,No,8,59,Low,Yes,2,Public,Female,61
2,24,98,Yes,7,91,Medium,Yes,2,Public,Male,74
3,29,89,Yes,8,98,Medium,Yes,1,Public,Male,71
4,19,92,Yes,6,65,Medium,Yes,3,Public,Female,70
...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,No,7,76,Medium,Yes,1,Public,Female,68
6603,23,76,No,8,81,Medium,Yes,3,Public,Female,69
6604,20,90,Yes,6,65,Low,Yes,3,Public,Female,68
6605,10,86,Yes,6,91,High,Yes,2,Private,Female,68
6606,15,67,Yes,9,94,Medium,Yes,0,Public,Male,64

In [7]:
print("Dataset_Info")
df.info()

Dataset_Info
<class 'pandas.core.frame.DataFrame'>
Index: 6378 entries, 0 to 6606
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6378 non-null   int64
 1   Attendance                  6378 non-null   int64
 2   Extracurricular_Activities  6378 non-null   object
 3   Sleep_Hours                 6378 non-null   int64
 4   Previous_Scores             6378 non-null   int64
 5   Motivation_Level            6378 non-null   object
 6   Internet_Access             6378 non-null   object
 7   Tutoring_Sessions           6378 non-null   int64
 8   School_Type                 6378 non-null   object
 9   Gender                      6378 non-null   object
 10  Exam_Score                  6378 non-null   int64
dtypes: int64(6), object(5)
memory usage: 597.9+ KB

In [8]:
# describe all numerical type columns
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Exam_Score
count,6378.000000,6378.000000,6378.000000,6378.000000,6378.000000,6378.000000
mean,19.977109,80.020853,7.034964,75.066165,1.495296,67.252117
std,5.985460,11.550723,1.468033,14.400389,1.233984,3.914217
min,1.000000,60.000000,4.000000,50.000000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.000000,101.000000

In [9]:
df

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,School_Type,Gender,Exam_Score
0,23,84,No,7,73,Low,Yes,0,Public,Male,67
1,19,64,No,8,59,Low,Yes,2,Public,Female,61
2,24,98,Yes,7,91,Medium,Yes,2,Public,Male,74
3,29,89,Yes,8,98,Medium,Yes,1,Public,Male,71
4,19,92,Yes,6,65,Medium,Yes,3,Public,Female,70
...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,No,7,76,Medium,Yes,1,Public,Female,68
6603,23,76,No,8,81,Medium,Yes,3,Public,Female,69
6604,20,90,Yes,6,65,Low,Yes,3,Public,Female,68
6605,10,86,Yes,6,91,High,Yes,2,Private,Female,68
6606,15,67,Yes,9,94,Medium,Yes,0,Public,Male,64

# Encode Categorical Values

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
df2 = df.copy()

df2

In [12]:
df2

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,School_Type,Gender,Exam_Score
0,23,84,No,7,73,Low,Yes,0,Public,Male,67
1,19,64,No,8,59,Low,Yes,2,Public,Female,61
2,24,98,Yes,7,91,Medium,Yes,2,Public,Male,74
3,29,89,Yes,8,98,Medium,Yes,1,Public,Male,71
4,19,92,Yes,6,65,Medium,Yes,3,Public,Female,70
...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,No,7,76,Medium,Yes,1,Public,Female,68
6603,23,76,No,8,81,Medium,Yes,3,Public,Female,69
6604,20,90,Yes,6,65,Low,Yes,3,Public,Female,68
6605,10,86,Yes,6,91,High,Yes,2,Private,Female,68
6606,15,67,Yes,9,94,Medium,Yes,0,Public,Male,64

In [13]:
df2.select_dtypes(include = "object").columns

Index(['Extracurricular_Activities', 'Motivation_Level', 'Internet_Access',
       'School_Type', 'Gender'],
      dtype='object')

In [14]:
le = LabelEncoder()

for col in df2.select_dtypes(include = "object").columns:
    df2[col] = le.fit_transform(df2[col])

In [15]:
df2

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,School_Type,Gender,Exam_Score
0,23,84,0,7,73,1,1,0,1,1,67
1,19,64,0,8,59,1,1,2,1,0,61
2,24,98,1,7,91,2,1,2,1,1,74
3,29,89,1,8,98,2,1,1,1,1,71
4,19,92,1,6,65,2,1,3,1,0,70
...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,0,7,76,2,1,1,1,0,68
6603,23,76,0,8,81,2,1,3,1,0,69
6604,20,90,1,6,65,1,1,3,1,0,68
6605,10,86,1,6,91,0,1,2,0,0,68
6606,15,67,1,9,94,2,1,0,1,1,64

# Feature Scalling

In [16]:
# StandardScaler

In [17]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [18]:
# standerd.scaler 
standard_scaler = StandardScaler()
standard_scaled = standard_scaler.fit_transform(df2)
df2_scale = round(pd.DataFrame(standard_scaled,columns=df.columns),2)
df2_scale

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,School_Type,Gender,Exam_Score
0,0.51,0.34,-1.22,-0.02,-0.14,-0.39,0.29,-1.21,0.66,0.85,-0.06
1,-0.16,-1.39,-1.22,0.66,-1.12,-0.39,0.29,0.41,0.66,-1.17,-1.60
2,0.67,1.56,0.82,-0.02,1.11,0.88,0.29,0.41,0.66,0.85,1.72
3,1.51,0.78,0.82,0.66,1.59,0.88,0.29,-0.40,0.66,0.85,0.96
4,-0.16,1.04,0.82,-0.71,-0.70,0.88,0.29,1.22,0.66,-1.17,0.70
...,...,...,...,...,...,...,...,...,...,...,...
6373,0.84,-0.95,-1.22,-0.02,0.06,0.88,0.29,-0.40,0.66,-1.17,0.19
6374,0.51,-0.35,-1.22,0.66,0.41,0.88,0.29,1.22,0.66,-1.17,0.45
6375,0.00,0.86,0.82,-0.71,-0.70,-0.39,0.29,1.22,0.66,-1.17,0.19
6376,-1.67,0.52,0.82,-0.71,1.11,-1.67,0.29,0.41,-1.51,-1.17,0.19
6377,-0.83,-1.13,0.82,1.34,1.31,0.88,0.29,-1.21,0.66,0.85,-0.83

In [19]:
# Minmax scaler

In [20]:
minmax_scaler = MinMaxScaler()
minmax_scaled = minmax_scaler.fit_transform(df2_scale)
print("\n\nMinMax Scaled Output")
df_fix = pd.DataFrame(minmax_scaled, columns = df2_scale.columns)

MinMax Scaled Output

# Split Training and Testing data

In [21]:
# split data

from  sklearn.model_selection import train_test_split 

X = df_fix[['Hours_Studied', 'Attendance',	'Extracurricular_Activities',	'Sleep_Hours',	'Previous_Scores',	'Motivation_Level',	'Internet_Access',	'Tutoring_Sessions',	'School_Type',	'Gender']]
y = df_fix['Exam_Score']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 34)

In [22]:
print("---------------------------------Training Data---------------------------------------")
X_train

---------------------------------Training Data---------------------------------------

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,School_Type,Gender
728,0.512535,0.349711,0.0,0.332518,1.000000,0.501961,1.0,0.250,0.0,1.0
928,0.419220,0.075145,1.0,0.501222,0.121037,1.000000,1.0,0.250,0.0,0.0
6047,0.395543,0.549133,1.0,0.332518,0.780980,0.000000,1.0,0.000,0.0,1.0
4191,0.512535,0.699422,0.0,0.667482,0.780980,1.000000,1.0,0.000,0.0,0.0
346,0.651811,0.424855,0.0,0.332518,0.700288,1.000000,1.0,0.125,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
3830,0.349582,0.523121,1.0,0.667482,0.141210,0.000000,1.0,0.125,0.0,1.0
5993,0.767409,0.823699,1.0,0.332518,0.861671,0.000000,1.0,0.250,1.0,1.0
2538,0.371866,0.950867,0.0,0.000000,0.121037,1.000000,1.0,0.250,0.0,0.0
5242,0.349582,0.248555,1.0,0.000000,0.700288,0.000000,1.0,0.000,0.0,1.0
3489,0.534819,0.523121,1.0,0.667482,0.559078,1.000000,1.0,0.125,1.0,1.0

In [23]:
print("-------------------------------Testing Data-------------------------------------------")
X_test

-------------------------------Testing Data-------------------------------------------

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,School_Type,Gender
949,0.278552,0.248555,0.0,1.000000,0.559078,1.000000,1.0,0.125,1.0,0.0
1473,0.488858,0.598266,1.0,0.166259,0.178674,1.000000,1.0,0.000,0.0,0.0
5987,0.232591,0.973988,1.0,0.501222,0.780980,0.000000,1.0,0.375,1.0,1.0
4074,0.441504,0.823699,0.0,0.332518,0.559078,0.501961,1.0,0.125,1.0,0.0
895,0.441504,0.725434,1.0,0.332518,0.481268,1.000000,1.0,0.125,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
2544,0.582173,0.575145,1.0,0.501222,0.780980,1.000000,1.0,0.375,0.0,1.0
2738,0.419220,0.424855,0.0,0.667482,0.060519,1.000000,1.0,0.125,0.0,1.0
5509,0.349582,0.973988,1.0,0.833741,0.100865,1.000000,1.0,0.125,1.0,0.0
169,0.325905,0.898844,0.0,0.501222,0.080692,0.000000,0.0,0.375,1.0,1.0
5664,0.349582,0.924855,1.0,0.667482,0.619597,0.000000,1.0,0.000,0.0,1.0

In [24]:
print("Training Data")
y_train

Training Data

728     0.282553
928     0.195745
6047    0.239149
4191    0.325957
346     0.304681
          ...
3830    0.239149
5993    0.478298
2538    0.304681
5242    0.195745
3489    0.282553
Name: Exam_Score, Length: 4464, dtype: float64

In [25]:
print("Testing Data")
y_test

Testing Data

949     0.130213
1473    0.304681
5987    0.369362
4074    0.325957
895     0.304681
          ...
2544    0.369362
2738    0.195745
5509    0.261277
169     0.261277
5664    0.325957
Name: Exam_Score, Length: 1914, dtype: float64

# KNN Algorithm

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
Knn = KNeighborsClassifier(n_neighbors = 5)

Knn.fit(X_train,y_train)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.