In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv("C:\\Datasets_ml\\placement-dataset.csv")
dataset

           city  cgpa     iq  placement
0      New York   6.8  123.0          1
1   Los Angeles   5.9  106.0          0
2       Chicago   NaN  121.0          0
3      New York   7.4  132.0          1
4   Los Angeles   5.8  142.0          0
..          ...   ...    ...        ...
95      Chicago   4.3  200.0          0
96     New York   4.4   42.0          0
97  Los Angeles   6.7  182.0          1
98      Chicago   6.3  103.0          1
99     New York   6.2  113.0          1

[100 rows x 4 columns]

In [3]:
dataset.isnull().sum()

city         0
cgpa         8
iq           4
placement    0
dtype: int64

In [4]:
dataset.isnull()

     city   cgpa     iq  placement
0   False  False  False      False
1   False  False  False      False
2   False   True  False      False
3   False  False  False      False
4   False  False  False      False
..    ...    ...    ...        ...
95  False  False  False      False
96  False  False  False      False
97  False  False  False      False
98  False  False  False      False
99  False  False  False      False

[100 rows x 4 columns]

In [5]:
dataset.head(5)

          city  cgpa     iq  placement
0     New York   6.8  123.0          1
1  Los Angeles   5.9  106.0          0
2      Chicago   NaN  121.0          0
3     New York   7.4  132.0          1
4  Los Angeles   5.8  142.0          0

In [6]:
from sklearn.impute import SimpleImputer
s1 = SimpleImputer(strategy = "mean")
dataset[['cgpa','iq']] = np.round(s1.fit_transform(dataset[["cgpa","iq"]]),2)

In [7]:
dataset

           city  cgpa     iq  placement
0      New York  6.80  123.0          1
1   Los Angeles  5.90  106.0          0
2       Chicago  5.97  121.0          0
3      New York  7.40  132.0          1
4   Los Angeles  5.80  142.0          0
..          ...   ...    ...        ...
95      Chicago  4.30  200.0          0
96     New York  4.40   42.0          0
97  Los Angeles  6.70  182.0          1
98      Chicago  6.30  103.0          1
99     New York  6.20  113.0          1

[100 rows x 4 columns]

In [10]:
cities = ['city_New York', 'city_Los Angeles', 'city_Chicago']
df_encoded[cities] = df_encoded[cities].astype(int)

NameError: name 'df_encoded' is not defined

In [11]:
df_encoded

NameError: name 'df_encoded' is not defined

In [12]:
from sklearn.preprocessing import LabelEncoder
la = LabelEncoder()
la.fit(dataset['city'])
arr = la.transform(dataset['city'])
dataset['city'] = pd.DataFrame(arr)
dataset

    city  cgpa     iq  placement
0      2  6.80  123.0          1
1      1  5.90  106.0          0
2      0  5.97  121.0          0
3      2  7.40  132.0          1
4      1  5.80  142.0          0
..   ...   ...    ...        ...
95     0  4.30  200.0          0
96     2  4.40   42.0          0
97     1  6.70  182.0          1
98     0  6.30  103.0          1
99     2  6.20  113.0          1

[100 rows x 4 columns]

In [13]:
x =  dataset[['city', 'cgpa', 'iq']]
y = dataset['placement']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 4)
print("Training data from x")
print(x_train)
print("\nTrianing Data from y")
print(y_train)

Training data from x
    city  cgpa     iq
80     0   4.9  196.0
4      1   5.8  142.0
81     2   5.4  107.0
76     1   4.9  155.0
85     1   5.8  166.0
..   ...   ...    ...
87     2   5.7  132.0
1      1   5.9  106.0
69     2   8.5  120.0
55     1   7.8  114.0
46     1   5.3  114.0

[80 rows x 3 columns]

Trianing Data from y
80    0
4     0
81    0
76    0
85    1
     ..
87    1
1     0
69    1
55    1
46    0
Name: placement, Length: 80, dtype: int64

In [14]:
print("Testing data from x",x_test)
print("\nTesting data from y",y_test)

Testing data from x     city  cgpa     iq
20     0  6.60  120.0
10     1  6.00   45.0
96     2  4.40   42.0
16     1  5.20  224.0
63     2  6.30  128.0
24     2  4.70  121.0
53     0  8.30  168.0
97     1  6.70  182.0
41     0  5.40  114.0
47     0  5.20  161.0
43     1  5.97  141.0
2      0  5.97  121.0
95     0  4.30  200.0
26     0  7.00  199.0
13     1  6.40  116.0
37     1  8.10  149.0
14     0  5.97  103.0
29     0  5.97    1.0
35     0  6.80   90.0
54     2  6.40  141.0

Testing data from y 20    1
10    1
96    0
16    0
63    1
24    0
53    1
97    1
41    0
47    0
43    1
2     0
95    0
26    1
13    1
37    1
14    0
29    0
35    1
54    1
Name: placement, dtype: int64

In [15]:
x =  dataset[['city','cgpa','iq']]
y = dataset['placement']
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [16]:

testing = x_train[['city','cgpa','iq']]
result = model.predict(testing)

In [17]:
for i in range(len(x_test)):
    if result[i] == 1:
        print("----Placed----")
    else:
        print("----Unplaced----")
    city_value = x_test.iloc[i]['city']
    if city_value == 2:
        print("city    New york")
    elif city_value == 1:
        print("city    Los Angeles")
    else:
        print("City    Chicago")
    print(x_test.iloc[i][['cgpa','iq']])
    print("________________________\n")

----Unplaced----
City    Chicago
cgpa      6.6
iq      120.0
Name: 20, dtype: float64
________________________

----Unplaced----
city    Los Angeles
cgpa     6.0
iq      45.0
Name: 10, dtype: float64
________________________

----Unplaced----
city    New york
cgpa     4.4
iq      42.0
Name: 96, dtype: float64
________________________

----Unplaced----
city    Los Angeles
cgpa      5.2
iq      224.0
Name: 16, dtype: float64
________________________

----Unplaced----
city    New york
cgpa      6.3
iq      128.0
Name: 63, dtype: float64
________________________

----Unplaced----
city    New york
cgpa      4.7
iq      121.0
Name: 24, dtype: float64
________________________

----Placed----
City    Chicago
cgpa      8.3
iq      168.0
Name: 53, dtype: float64
________________________

----Placed----
city    Los Angeles
cgpa      6.7
iq      182.0
Name: 97, dtype: float64
________________________

----Unplaced----
City    Chicago
cgpa      5.4
iq      114.0
Name: 41, dtype: float64
________________________

----Unplaced----
City    Chicago
cgpa      5.2
iq      161.0
Name: 47, dtype: float64
________________________

----Placed----
city    Los Angeles
cgpa      5.97
iq      141.00
Name: 43, dtype: float64
________________________

----Unplaced----
City    Chicago
cgpa      5.97
iq      121.00
Name: 2, dtype: float64
________________________

----Unplaced----
City    Chicago
cgpa      4.3
iq      200.0
Name: 95, dtype: float64
________________________

----Unplaced----
City    Chicago
cgpa      7.0
iq      199.0
Name: 26, dtype: float64
________________________

----Placed----
city    Los Angeles
cgpa      6.4
iq      116.0
Name: 13, dtype: float64
________________________

----Unplaced----
city    Los Angeles
cgpa      8.1
iq      149.0
Name: 37, dtype: float64
________________________

----Unplaced----
City    Chicago
cgpa      5.97
iq      103.00
Name: 14, dtype: float64
________________________

----Unplaced----
City    Chicago
cgpa    5.97
iq      1.00
Name: 29, dtype: float64
________________________

----Unplaced----
City    Chicago
cgpa     6.8
iq      90.0
Name: 35, dtype: float64
________________________

----Unplaced----
city    New york
cgpa      6.4
iq      141.0
Name: 54, dtype: float64
________________________

In [18]:
from mlxtend.plotting import plot_decision_regions

ModuleNotFoundError: No module named 'mlxtend'