# Handel missing value

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name' : ['Pawan','kapil','Lalit','Ishan','Om'],
    'Age' : [25,None,44,23,None],
    'Salary' : [50000,60000, 70000, None,None]
}
df = pd.DataFrame(data)
df

    Name   Age   Salary
0  Pawan  25.0  50000.0
1  kapil   NaN  60000.0
2  Lalit  44.0  70000.0
3  Ishan  23.0      NaN
4     Om   NaN      NaN

In [3]:
# isnull().sum()
print(df.isnull().sum())

Name      0
Age       2
Salary    2
dtype: int64

In [4]:
#  total null vlaue
df.isnull().sum().sum()

np.int64(4)

In [5]:
dataF = df.copy()
dataF

    Name   Age   Salary
0  Pawan  25.0  50000.0
1  kapil   NaN  60000.0
2  Lalit  44.0  70000.0
3  Ishan  23.0      NaN
4     Om   NaN      NaN

In [6]:
df['Age'].mean()

np.float64(30.666666666666668)

In [7]:
dataF['Age'].fillna(dataF['Age'].mean(),inplace=True)
dataF

C:\Users\jiyad\AppData\Local\Temp\ipykernel_8172\2765560217.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataF['Age'].fillna(dataF['Age'].mean(),inplace=True)

    Name        Age   Salary
0  Pawan  25.000000  50000.0
1  kapil  30.666667  60000.0
2  Lalit  44.000000  70000.0
3  Ishan  23.000000      NaN
4     Om  30.666667      NaN

# Encode Categorical Values

In [8]:
data = {
    'Name': ['Aditi', 'Rohan', 'Priya', 'Arjun', 'Sneha', 'Karan', 'Neha', 'Raj'],
    'Gender': ['Female', 'Male', None, 'Male', 'Female', 'Male', 'Female', None],
    'Department': ['CSE', 'AIML', 'IT', None, 'ECE', 'IT', 'AIML', 'CSE'],
    'Age': [19, None, 18, 21, 20, None, 22, 20],
    'CGPA': [8.5, 7.8, None, 7.2, 8.8, 8.1, 9.0, None],
    'City': ['Indore', 'Bhopal', 'Ujjain', 'Indore', None, 'Pune', 'Bhopal', 'Indore']
}

In [9]:
dataset = pd.DataFrame(data)
dataset

    Name  Gender Department   Age  CGPA    City
0  Aditi  Female        CSE  19.0   8.5  Indore
1  Rohan    Male       AIML   NaN   7.8  Bhopal
2  Priya    None         IT  18.0   NaN  Ujjain
3  Arjun    Male       None  21.0   7.2  Indore
4  Sneha  Female        ECE  20.0   8.8    None
5  Karan    Male         IT   NaN   8.1    Pune
6   Neha  Female       AIML  22.0   9.0  Bhopal
7    Raj    None        CSE  20.0   NaN  Indore

In [10]:
dataset.isnull().sum()

Name          0
Gender        2
Department    1
Age           2
CGPA          2
City          1
dtype: int64

In [11]:
dataset.isnull().sum().sum()

np.int64(8)

In [12]:
dataset.select_dtypes(include = 'float64')

    Age  CGPA
0  19.0   8.5
1   NaN   7.8
2  18.0   NaN
3  21.0   7.2
4  20.0   8.8
5   NaN   8.1
6  22.0   9.0
7  20.0   NaN

In [13]:
print(dataset['Age'].mean())
print(dataset['CGPA'].mean())

20.0
8.233333333333333

In [14]:
# fill numerical nulll value by call sklearn library

In [15]:
from sklearn.impute import SimpleImputer

In [16]:
si = SimpleImputer(strategy = "mean")

In [17]:
dataset[['Age', 'CGPA']] = si.fit_transform(dataset[['Age', 'CGPA']])
dataset

    Name  Gender Department   Age      CGPA    City
0  Aditi  Female        CSE  19.0  8.500000  Indore
1  Rohan    Male       AIML  20.0  7.800000  Bhopal
2  Priya    None         IT  18.0  8.233333  Ujjain
3  Arjun    Male       None  21.0  7.200000  Indore
4  Sneha  Female        ECE  20.0  8.800000    None
5  Karan    Male         IT  20.0  8.100000    Pune
6   Neha  Female       AIML  22.0  9.000000  Bhopal
7    Raj    None        CSE  20.0  8.233333  Indore

In [18]:
# decrease moredecimal value after point in 2 value only
dataset['CGPA'] = dataset['CGPA'].round(2)

In [19]:
dataset

    Name  Gender Department   Age  CGPA    City
0  Aditi  Female        CSE  19.0  8.50  Indore
1  Rohan    Male       AIML  20.0  7.80  Bhopal
2  Priya    None         IT  18.0  8.23  Ujjain
3  Arjun    Male       None  21.0  7.20  Indore
4  Sneha  Female        ECE  20.0  8.80    None
5  Karan    Male         IT  20.0  8.10    Pune
6   Neha  Female       AIML  22.0  9.00  Bhopal
7    Raj    None        CSE  20.0  8.23  Indore

# fill catagorical data

In [20]:
from sklearn.impute import SimpleImputer

In [21]:
dataset =dataset.replace({None: np.nan})

In [22]:
si = SimpleImputer(strategy = "most_frequent")
dataset[['Gender','Department','City']] = si.fit_transform(dataset[['Gender','Department','City']])

In [23]:
dataset

    Name  Gender Department   Age  CGPA    City
0  Aditi  Female        CSE  19.0  8.50  Indore
1  Rohan    Male       AIML  20.0  7.80  Bhopal
2  Priya  Female         IT  18.0  8.23  Ujjain
3  Arjun    Male       AIML  21.0  7.20  Indore
4  Sneha  Female        ECE  20.0  8.80  Indore
5  Karan    Male         IT  20.0  8.10    Pune
6   Neha  Female       AIML  22.0  9.00  Bhopal
7    Raj  Female        CSE  20.0  8.23  Indore

# Encode Categorical values

In [24]:
# 1. label Encoding 
'''
Gender    Encoder
Male        0
Female      1
'''

'\nGender    Encoder\nMale        0\nFemale      1\n'

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
dataset = {
    'Name': ['Aditi', 'Rohan', 'Priya', 'Arjun', 'Sneha', 'Kabir', 'Isha', 'Vikram'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male'],
    'Department': ['CSE', 'AIML', 'IT', 'CSE', 'AIML', 'IT', 'CSE', 'AIML'],
    'Hostel': ['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'],
    'Scholarship': ['True', 'False', 'True', 'True', 'False', 'False', 'True', 'True'],
    'City': ['Indore', 'Bhopal', 'Ujjain', 'Indore', 'Bhopal', 'Ujjain', 'Indore', 'Bhopal']
}

In [27]:
new_dataset = pd.DataFrame(dataset)
new_dataset

     Name  Gender Department Hostel Scholarship    City
0   Aditi  Female        CSE    Yes        True  Indore
1   Rohan    Male       AIML     No       False  Bhopal
2   Priya  Female         IT    Yes        True  Ujjain
3   Arjun    Male        CSE     No        True  Indore
4   Sneha  Female       AIML    Yes       False  Bhopal
5   Kabir    Male         IT     No       False  Ujjain
6    Isha  Female        CSE    Yes        True  Indore
7  Vikram    Male       AIML     No        True  Bhopal

In [28]:
df = new_dataset.copy()
df

     Name  Gender Department Hostel Scholarship    City
0   Aditi  Female        CSE    Yes        True  Indore
1   Rohan    Male       AIML     No       False  Bhopal
2   Priya  Female         IT    Yes        True  Ujjain
3   Arjun    Male        CSE     No        True  Indore
4   Sneha  Female       AIML    Yes       False  Bhopal
5   Kabir    Male         IT     No       False  Ujjain
6    Isha  Female        CSE    Yes        True  Indore
7  Vikram    Male       AIML     No        True  Bhopal

In [35]:
df.isnull().sum()

Name           0
Gender         0
Department     0
Hostel         0
Scholarship    0
City           0
dtype: int64

In [36]:
from sklearn.preprocessing import LabelEncoder

In [64]:
le = LabelEncoder()
df['Gender_Encoded']  = le.fit_transform(df['Gender'])
df['Hostel_Encoded'] = le.fit_transform(df['Hostel'])
df['Scholarship_Encoded'] = le.fit_transform(df['Scholarship'])

In [65]:
for col in df.columns:
    print(f"'{col}'")

'Name'
'Gender'
'Department'
'Hostel'
'Scholarship'
'City'
'Gender_Encoded'
'Hostel_Encoded'
'Scholarship_Encoded'
'Gender_E'
'Hostel_E'
'Scholarship_E'

In [66]:
print('Label Encoder Dataa')
(df[['Name','Gender','Gender_Encoded','Department','Hostel','Hostel_E','Scholarship','Scholarship_E','City']])

Label Encoder Dataa

,Name,Gender,Gender_Encoded,Department,Hostel,Hostel_Encoded,Scholarship,Scholarship_Encoded,City
0,Aditi,Female,0,CSE,1,1,True,1,Indore
1,Rohan,Male,1,AIML,0,0,False,0,Bhopal
2,Priya,Female,0,IT,1,1,True,1,Ujjain
3,Arjun,Male,1,CSE,0,0,True,1,Indore
4,Sneha,Female,0,AIML,1,1,False,0,Bhopal
5,Kabir,Male,1,IT,0,0,False,0,Ujjain
6,Isha,Female,0,CSE,1,1,True,1,Indore
7,Vikram,Male,1,AIML,0,0,True,1,Bhopal

# 2. One - Hot Encoding

In [71]:
# 2. One-Hot Encoding
df_encoded = pd.get_dummies(new_dataset, columns = ['City'])  # text columns to converet small binary number
print('One Hot Encoded Data of the (City)')
df_encoded

One Hot Encoded Data of the (City)

,Name,Gender,Department,Hostel,Scholarship,City_Bhopal,City_Indore,City_Ujjain
0,Aditi,Female,CSE,Yes,True,False,True,False
1,Rohan,Male,AIML,No,False,True,False,False
2,Priya,Female,IT,Yes,True,False,False,True
3,Arjun,Male,CSE,No,True,False,True,False
4,Sneha,Female,AIML,Yes,False,True,False,False
5,Kabir,Male,IT,No,False,False,False,True
6,Isha,Female,CSE,Yes,True,False,True,False
7,Vikram,Male,AIML,No,True,True,False,False

In [79]:
l=[]
for col in df_encoded.columns:
    l.append(col)
print(l)

['Name', 'Gender', 'Department', 'Hostel', 'Scholarship', 'City_Bhopal', 'City_Indore', 'City_Ujjain']

In [81]:
# convert the object type data of city in numerical type
cols_to_convert  = ['City_Bhopal','City_Indore','City_Ujjain']
df_encoded[cols_to_convert] = df_encoded[cols_to_convert].astype(int)   # converet into numerical type
df_encoded

,Name,Gender,Department,Hostel,Scholarship,City_Bhopal,City_Indore,City_Ujjain
0,Aditi,Female,CSE,Yes,True,0,1,0
1,Rohan,Male,AIML,No,False,1,0,0
2,Priya,Female,IT,Yes,True,0,0,1
3,Arjun,Male,CSE,No,True,0,1,0
4,Sneha,Female,AIML,Yes,False,1,0,0
5,Kabir,Male,IT,No,False,0,0,1
6,Isha,Female,CSE,Yes,True,0,1,0
7,Vikram,Male,AIML,No,True,1,0,0

# 3. Feature Scaling

In [87]:
import pandas as pd
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.model_selection import train_test_split

In [96]:
data = {
    'Study Hours' : [1,2,3,4,5,6],
    'Test Scores' : [20,30,40,50,60,70]
}

df=pd.DataFrame(data)

#standardscaler
standard_scaler = StandardScaler()
standard_scaled = standard_scaler.fit_transform(df)

print("Standarf Scaled Output : ")
print(pd.DataFrame(standard_scaled, columns = ['Study Hours' , 'Test Score' ]))

#minaxScaler
minmax_scaler = MinMaxScaler()
minmax_scaled = minmax_scaler.fit_transform(df)

print("\n\n MinMax Scaled Output : ")
print(pd.DataFrame(minmax_scaled,columns = ['Study Hours','TestScore']))

Standarf Scaled Output :
   Study Hours  Test Score
0     -1.46385    -1.46385
1     -0.87831    -0.87831
2     -0.29277    -0.29277
3      0.29277     0.29277
4      0.87831     0.87831
5      1.46385     1.46385


 MinMax Scaled Output :
   Study Hours  TestScore
0          0.0        0.0
1          0.2        0.2
2          0.4        0.4
3          0.6        0.6
4          0.8        0.8
5          1.0        1.0

# 4. Split Data

In [105]:
x = df[['Study Hours']]
y = df[['Test Scores']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state=2)
print("\nTrainig Data")
print(x_train)

print("\nTesting Data")
print(x_test)

print("\nTraining Data")
print(y_train)

print("\nTesting Data")
print(y_test)

Trainig Data
   Study Hours
3            4
2            3
5            6
0            1

Testing Data
   Study Hours
4            5
1            2

Training Data
   Test Scores
3           50
2           40
5           70
0           20

Testing Data
   Test Scores
4           60
1           30