In [1]:
import numpy as np
import pandas as pd

In [2]:
dic1={
    'name':['jiya','riya','harshu','mahima'],
    'marks':[98,78,89,78],
    'city':["indore","betul",'delhi','mumbai']
    
}

In [3]:
#dataframe like a exel sheet in python
df=pd.DataFrame(dic1)
df

     name  marks    city
0    jiya     98  indore
1    riya     78   betul
2  harshu     89   delhi
3  mahima     78  mumbai

In [4]:
#for put in excel sheet
df.to_csv("behancode.csv")

In [5]:
#for delete the index coloum
df.to_csv("friends_index_false.csv",index=False)

In [6]:
#for showing starting row only
df.head(2)

   name  marks    city
0  jiya     98  indore
1  riya     78   betul

In [7]:
#for showing last row only
df.tail(2)

     name  marks    city
2  harshu     89   delhi
3  mahima     78  mumbai

In [8]:
#describe only numerical coloum
df.describe()

           marks
count   4.000000
mean   85.750000
std     9.673848
min    78.000000
25%    78.000000
50%    83.500000
75%    91.250000
max    98.000000

In [9]:
j={
    'Train':[6564,44555,7734,83583],
    'city':["dlehi",'indore','raipur']
}

In [10]:
j.to_csv("jiya.csv")

AttributeError: 'dict' object has no attribute 'to_csv'

In [11]:
#for read the sheet
ji=pd.read_csv("bahancode.csv")

In [12]:
ji

   Unnamed: 0    name  marks    city
0           0    jiya     98  indore
1           1    riya     78   betul
2           2  harshu     89   delhi
3           3  mahima     78  mumbai

In [13]:
ji['marks']

0    98
1    78
2    89
3    78
Name: marks, dtype: int64

In [14]:
jiya['name']

NameError: name 'jiya' is not defined

In [15]:
ji['marks'][0]

np.int64(98)

In [16]:
print(ji['name'][0])
print(ji['name'][2])

jiya
harshu

In [17]:
ji['city'][0]='chandigadh'

C:\Users\jiyad\AppData\Local\Temp\ipykernel_14632\640652492.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ji['city'][0]='chandigadh'
C:\Users\jiyad\AppData\Local\Temp\ipykernel_14632\640652492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ji['city'][0]='chandigadh'

In [18]:
ji

   Unnamed: 0    name  marks        city
0           0    jiya     98  chandigadh
1           1    riya     78       betul
2           2  harshu     89       delhi
3           3  mahima     78      mumbai

In [19]:
ji['name'][2]='kanak'

C:\Users\jiyad\AppData\Local\Temp\ipykernel_14632\4107078085.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ji['name'][2]='kanak'
C:\Users\jiyad\AppData\Local\Temp\ipykernel_14632\4107078085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ji['name'][2]='kanak'

In [20]:
ji

   Unnamed: 0    name  marks        city
0           0    jiya     98  chandigadh
1           1    riya     78       betul
2           2   kanak     89       delhi
3           3  mahima     78      mumbai

In [21]:
ji.to_csv('djiya.csv')

In [22]:
#ji=pd.read_csv("djiya.csv",delimiter=",")

In [23]:
#ji=ji.drop(columns=['Unnamed:0'])
#print(ji)

In [24]:
#replace index this name
ji.index=["first",'second','third','forth']
ji

        Unnamed: 0    name  marks        city
first            0    jiya     98  chandigadh
second           1    riya     78       betul
third            2   kanak     89       delhi
forth            3  mahima     78      mumbai

In [25]:
dic={
    'student':['rohan','swati','payal','mukul'],
    'marks':[22,33,44,23],
    'roll-no': [23,45,67,89]
}

In [26]:
dic3=pd.DataFrame(dic)
dic3

  student  marks  roll-no
0   rohan     22       23
1   swati     33       45
2   payal     44       67
3   mukul     23       89

In [27]:
dic3.to_csv("Dictionary.csv")

In [28]:
#replace index
dic3.index=["student-1","student-2","student-3","student-4"]
dic3

          student  marks  roll-no
student-1   rohan     22       23
student-2   swati     33       45
student-3   payal     44       67
student-4   mukul     23       89

In [29]:
ser=pd.Series(np.random.rand(50))
ser

0     0.396539
1     0.374199
2     0.189290
3     0.070713
4     0.079468
5     0.539273
6     0.407137
7     0.059456
8     0.206123
9     0.160244
10    0.136816
11    0.698736
12    0.179404
13    0.405358
14    0.450450
15    0.057736
16    0.904297
17    0.940484
18    0.938810
19    0.065380
20    0.814908
21    0.047916
22    0.334504
23    0.754380
24    0.244129
25    0.670026
26    0.285044
27    0.327607
28    0.818768
29    0.011167
30    0.182971
31    0.661420
32    0.904627
33    0.256649
34    0.509685
35    0.983842
36    0.355975
37    0.788143
38    0.796610
39    0.256929
40    0.440626
41    0.474723
42    0.217695
43    0.483609
44    0.146677
45    0.844699
46    0.074186
47    0.501179
48    0.932373
49    0.554072
dtype: float64

In [30]:
type(ser)

pandas.core.series.Series

In [31]:
#dataframe
newdf=pd.DataFrame(np.random.rand(330,6),index=np.arange(330))
newdf

            0         1         2         3         4         5
0    0.038060  0.997278  0.640207  0.911423  0.046874  0.617678
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4    0.313650  0.017235  0.678296  0.122868  0.432124  0.637605
..        ...       ...       ...       ...       ...       ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329  0.763430  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [32]:
newdf.head(10)

          0         1         2         3         4         5
0  0.038060  0.997278  0.640207  0.911423  0.046874  0.617678
1  0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2  0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3  0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4  0.313650  0.017235  0.678296  0.122868  0.432124  0.637605
5  0.494384  0.595772  0.784698  0.891079  0.367520  0.695004
6  0.532989  0.558354  0.498494  0.377730  0.135734  0.924506
7  0.810975  0.218343  0.525093  0.643984  0.084476  0.997508
8  0.780475  0.270249  0.178761  0.145423  0.491113  0.943296
9  0.035217  0.988387  0.567058  0.183368  0.848773  0.777643

In [33]:
newdf.tail(5)

            0         1         2         3         4         5
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329  0.763430  0.340184  0.860948  0.849909  0.865885  0.217861

In [34]:
#type
type(newdf)

pandas.core.frame.DataFrame

In [35]:
newdf.describe()

                0           1           2           3           4           5
count  330.000000  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.502195    0.505658    0.493470    0.485876    0.515099    0.480456
std      0.294886    0.301022    0.278075    0.286580    0.291266    0.291288
min      0.001238    0.005656    0.000923    0.006090    0.001515    0.008893
25%      0.238576    0.237383    0.260602    0.248260    0.254619    0.230445
50%      0.497220    0.520126    0.501998    0.467297    0.533683    0.459181
75%      0.747617    0.779300    0.703786    0.728314    0.779889    0.747541
max      0.998338    0.999080    0.999344    0.995883    0.999660    0.998125

In [36]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
dtype: object

In [37]:
newdf[0][0]="jiya"
newdf.head(3)

C:\Users\jiyad\AppData\Local\Temp\ipykernel_14632\753694822.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]="jiya"
C:\Users\jiyad\AppData\Local\Temp\ipykernel_14632\753694822.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'jiya' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]="jiya"

          0         1         2         3         4         5
0      jiya  0.997278  0.640207  0.911423  0.046874  0.617678
1  0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2  0.821859  0.799327  0.914633  0.105097  0.711592  0.143115

In [38]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
5    float64
dtype: object

In [39]:
#print index
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       320, 321, 322, 323, 324, 325, 326, 327, 328, 329],
      dtype='int64', length=330)

In [40]:
#print columns
newdf.columns

RangeIndex(start=0, stop=6, step=1)

In [41]:
#panda convert into numpy array
newdf.to_numpy()

array([['jiya', 0.9972779608128718, 0.6402074972189687,
        0.9114227563407776, 0.04687446104039916, 0.6176776734828802],
       [0.4920759945917259, 0.8678471773910075, 0.8457628876711784,
        0.9342690711729854, 0.2985266897190739, 0.11966643786867492],
       [0.821859353640226, 0.7993273078371618, 0.9146326042525375,
        0.10509694588389207, 0.7115915921880354, 0.14311465257926548],
       ...,
       [0.4875133663572475, 0.5346398131405234, 0.5682068321002183,
        0.9082932408612064, 0.03785100472348557, 0.7393814266179805],
       [0.8382926313691832, 0.5849943456374047, 0.6709415166009735,
        0.9093207142384868, 0.38113928343940395, 0.28737242215859304],
       [0.7634298530101227, 0.34018380627131395, 0.8609484957235828,
        0.8499088661090287, 0.8658848941519827, 0.21786144149934594]],
      dtype=object)

In [42]:
#replace jiya from 0.3 of first index of array
newdf[0][0]=0.3 
newdf

            0         1         2         3         4         5
0         0.3  0.997278  0.640207  0.911423  0.046874  0.617678
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605
..        ...       ...       ...       ...       ...       ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [43]:
#for transpose the element T is used
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,320,321,322,323,324,325,326,327,328,329
0,0.3,0.492076,0.821859,0.794002,0.31365,0.494384,0.532989,0.810975,0.780475,0.035217,...,0.130164,0.655874,0.633009,0.341574,0.928809,0.975059,0.458002,0.487513,0.838293,0.76343
1,0.997278,0.867847,0.799327,0.138469,0.017235,0.595772,0.558354,0.218343,0.270249,0.988387,...,0.462568,0.958898,0.046736,0.456835,0.15007,0.520815,0.086683,0.53464,0.584994,0.340184
2,0.640207,0.845763,0.914633,0.112882,0.678296,0.784698,0.498494,0.525093,0.178761,0.567058,...,0.563302,0.010917,0.383022,0.354842,0.028785,0.194732,0.370212,0.568207,0.670942,0.860948
3,0.911423,0.934269,0.105097,0.068699,0.122868,0.891079,0.37773,0.643984,0.145423,0.183368,...,0.62211,0.82961,0.567595,0.895527,0.684943,0.145344,0.958286,0.908293,0.909321,0.849909
4,0.046874,0.298527,0.711592,0.516275,0.432124,0.36752,0.135734,0.084476,0.491113,0.848773,...,0.088281,0.595005,0.357945,0.28302,0.826832,0.788843,0.262827,0.037851,0.381139,0.865885
5,0.617678,0.119666,0.143115,0.786145,0.637605,0.695004,0.924506,0.997508,0.943296,0.777643,...,0.089296,0.593437,0.721866,0.059064,0.111524,0.355216,0.033402,0.739381,0.287372,0.217861

In [44]:
newdf[0]

0           0.3
1      0.492076
2      0.821859
3      0.794002
4       0.31365
         ...
325    0.975059
326    0.458002
327    0.487513
328    0.838293
329     0.76343
Name: 0, Length: 330, dtype: object

In [45]:
type(newdf[0])

pandas.core.series.Series

In [46]:
#newdf2 is only the view of newdf if we change in newdf2 so automatically change is created in newdf
newdf2 = newdf

In [47]:
newdf[0][0]=76586
newdf
#now we print newdf but we can not do any change in newdf so view of newdf is newdf2's value is added in newdf

            0         1         2         3         4         5
0       76586  0.997278  0.640207  0.911423  0.046874  0.617678
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605
..        ...       ...       ...       ...       ...       ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [48]:
newdf2=newdf.copy()

newdf2=[0][0]=765345

In [49]:
newdf
#now this time not any changes in newdf because we already make copy file of newdf thats why

            0         1         2         3         4         5
0       76586  0.997278  0.640207  0.911423  0.046874  0.617678
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605
..        ...       ...       ...       ...       ...       ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [50]:
#change the columns name
newdf.columns=list('PQRSTU')
newdf

            P         Q         R         S         T         U
0       76586  0.997278  0.640207  0.911423  0.046874  0.617678
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605
..        ...       ...       ...       ...       ...       ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [51]:
#if i chnage index 0,0
newdf.loc[0,0]=99685
print(newdf)
# now other column will added so we can't write 0,0 we write 0,p

            P         Q         R         S         T         U        0
0       76586  0.997278  0.640207  0.911423  0.046874  0.617678  99685.0
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666      NaN
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115      NaN
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145      NaN
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605      NaN
..        ...       ...       ...       ...       ...       ...      ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216      NaN
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402      NaN
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381      NaN
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372      NaN
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861      NaN

[330 rows x 7 columns]

In [52]:
newdf.loc[0,'P']=73
newdf

            P         Q         R         S         T         U        0
0          73  0.997278  0.640207  0.911423  0.046874  0.617678  99685.0
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666      NaN
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115      NaN
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145      NaN
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605      NaN
..        ...       ...       ...       ...       ...       ...      ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216      NaN
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402      NaN
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381      NaN
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372      NaN
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861      NaN

[330 rows x 7 columns]

In [53]:
# i don't want last coloum so we will doing 
#if we put axis 1 so last column is and if we put axis =0 so first row will delete
new=newdf.drop(0,axis=1)
new

            P         Q         R         S         T         U
0          73  0.997278  0.640207  0.911423  0.046874  0.617678
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605
..        ...       ...       ...       ...       ...       ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [54]:
#if i want a particular element in the whole data frame so
new.loc[[1,2],["Q","R"]]

          Q         R
1  0.867847  0.845763
2  0.799327  0.914633

In [55]:
#data is not change for want a perticular colummn and row data
new.head()

          P         Q         R         S         T         U
0        73  0.997278  0.640207  0.911423  0.046874  0.617678
1  0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2  0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3  0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4   0.31365  0.017235  0.678296  0.122868  0.432124  0.637605

In [56]:
#if i want a particular column but whole rows 
new.loc[:,['P','Q']]

            P         Q
0          73  0.997278
1    0.492076  0.867847
2    0.821859  0.799327
3    0.794002  0.138469
4     0.31365  0.017235
..        ...       ...
325  0.975059  0.520815
326  0.458002  0.086683
327  0.487513  0.534640
328  0.838293  0.584994
329   0.76343  0.340184

[330 rows x 2 columns]

In [57]:
#if we want a particular row but whole column so
new.loc[[44,45],:]

           P         Q         R         S         T         U
44  0.746962  0.437188  0.123743  0.345368  0.780648  0.087193
45  0.219677  0.284576  0.212639  0.006090  0.658408  0.409652

In [58]:
#loc
new.loc[(new["P"]<o.3)]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1220021236.py, line 2)

In [59]:
# iloc help to print any index by nu nemerical name
new.iloc[0,3]

np.float64(0.9114227563407776)

In [60]:
new.iloc[[0,5],[2,4]]

          R         T
0  0.640207  0.046874
5  0.784698  0.367520

In [61]:
#if i want to delete any row like
new.drop([0]) #now 0th row is deleted

            P         Q         R         S         T         U
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605
5    0.494384  0.595772  0.784698  0.891079  0.367520  0.695004
..        ...       ...       ...       ...       ...       ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861

[329 rows x 6 columns]

In [62]:
# i want to delete some both column and row
new.drop(['P','U'],axis=1)

            Q         R         S         T
0    0.997278  0.640207  0.911423  0.046874
1    0.867847  0.845763  0.934269  0.298527
2    0.799327  0.914633  0.105097  0.711592
3    0.138469  0.112882  0.068699  0.516275
4    0.017235  0.678296  0.122868  0.432124
..        ...       ...       ...       ...
325  0.520815  0.194732  0.145344  0.788843
326  0.086683  0.370212  0.958286  0.262827
327  0.534640  0.568207  0.908293  0.037851
328  0.584994  0.670942  0.909321  0.381139
329  0.340184  0.860948  0.849909  0.865885

[330 rows x 4 columns]

In [63]:
#inclace means delete the coloum of a and d in orginal content
new.drop(['R','S'],axis=1,inplace=True)

In [64]:
new
#r ans s column delete permanentaly fron new

            P         Q         T         U
0          73  0.997278  0.046874  0.617678
1    0.492076  0.867847  0.298527  0.119666
2    0.821859  0.799327  0.711592  0.143115
3    0.794002  0.138469  0.516275  0.786145
4     0.31365  0.017235  0.432124  0.637605
..        ...       ...       ...       ...
325  0.975059  0.520815  0.788843  0.355216
326  0.458002  0.086683  0.262827  0.033402
327  0.487513  0.534640  0.037851  0.739381
328  0.838293  0.584994  0.381139  0.287372
329   0.76343  0.340184  0.865885  0.217861

[330 rows x 4 columns]

In [65]:
newdf.drop([0],axis=1,inplace=True)

In [66]:
newdf

            P         Q         R         S         T         U
0          73  0.997278  0.640207  0.911423  0.046874  0.617678
1    0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2    0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3    0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4     0.31365  0.017235  0.678296  0.122868  0.432124  0.637605
..        ...       ...       ...       ...       ...       ...
325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [67]:
newdf.head(4)

          P         Q         R         S         T         U
0        73  0.997278  0.640207  0.911423  0.046874  0.617678
1  0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2  0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3  0.794002  0.138469  0.112882  0.068699  0.516275  0.786145

In [68]:
newdf.reset_index()

     index         P         Q         R         S         T         U
0        0        73  0.997278  0.640207  0.911423  0.046874  0.617678
1        1  0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2        2  0.821859  0.799327  0.914633  0.105097  0.711592  0.143115
3        3  0.794002  0.138469  0.112882  0.068699  0.516275  0.786145
4        4   0.31365  0.017235  0.678296  0.122868  0.432124  0.637605
..     ...       ...       ...       ...       ...       ...       ...
325    325  0.975059  0.520815  0.194732  0.145344  0.788843  0.355216
326    326  0.458002  0.086683  0.370212  0.958286  0.262827  0.033402
327    327  0.487513  0.534640  0.568207  0.908293  0.037851  0.739381
328    328  0.838293  0.584994  0.670942  0.909321  0.381139  0.287372
329    329   0.76343  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 7 columns]

In [69]:
#for removing one more 0th index added in sheet we can write

In [70]:
newdf.reset_index(drop=True,inplace=True)
newdf.head(3)  #look 0th column is deleted

          P         Q         R         S         T         U
0        73  0.997278  0.640207  0.911423  0.046874  0.617678
1  0.492076  0.867847  0.845763  0.934269  0.298527  0.119666
2  0.821859  0.799327  0.914633  0.105097  0.711592  0.143115

In [71]:
newdf['P']=None
newdf

        P         Q         R         S         T         U
0    None  0.997278  0.640207  0.911423  0.046874  0.617678
1    None  0.867847  0.845763  0.934269  0.298527  0.119666
2    None  0.799327  0.914633  0.105097  0.711592  0.143115
3    None  0.138469  0.112882  0.068699  0.516275  0.786145
4    None  0.017235  0.678296  0.122868  0.432124  0.637605
..    ...       ...       ...       ...       ...       ...
325  None  0.520815  0.194732  0.145344  0.788843  0.355216
326  None  0.086683  0.370212  0.958286  0.262827  0.033402
327  None  0.534640  0.568207  0.908293  0.037851  0.739381
328  None  0.584994  0.670942  0.909321  0.381139  0.287372
329  None  0.340184  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [72]:
newdf['P'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
325    True
326    True
327    True
328    True
329    True
Name: P, Length: 330, dtype: bool

In [73]:
newdf.loc[:,['Q']]='jiya'
newdf

C:\Users\jiyad\AppData\Local\Temp\ipykernel_14632\311985898.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'jiya' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf.loc[:,['Q']]='jiya'

        P     Q         R         S         T         U
0    None  jiya  0.640207  0.911423  0.046874  0.617678
1    None  jiya  0.845763  0.934269  0.298527  0.119666
2    None  jiya  0.914633  0.105097  0.711592  0.143115
3    None  jiya  0.112882  0.068699  0.516275  0.786145
4    None  jiya  0.678296  0.122868  0.432124  0.637605
..    ...   ...       ...       ...       ...       ...
325  None  jiya  0.194732  0.145344  0.788843  0.355216
326  None  jiya  0.370212  0.958286  0.262827  0.033402
327  None  jiya  0.568207  0.908293  0.037851  0.739381
328  None  jiya  0.670942  0.909321  0.381139  0.287372
329  None  jiya  0.860948  0.849909  0.865885  0.217861

[330 rows x 6 columns]

In [74]:
d = {'aryan': ['NA',10,'nanakheda'], 
     'harsh': ['MA',20,'Chaukidhani'], 
     'kunal': ['MLA','lalitpur','30'],}

In [75]:
p=pd.DataFrame(d)

In [76]:
p

       aryan        harsh     kunal
0         NA           MA       MLA
1         10           20  lalitpur
2  nanakheda  Chaukidhani        30

In [77]:
p.loc[:,['0','aryan']]

KeyError: "['0'] not in index"

In [ ]:
f={
    'name':['jiya',"sandhya","khnaak","drashti"],
    "age":[18,19,20,21],
    "ROLLNO":[63,111,66,51]
}

In [ ]:
S=pd.DataFrame(f)

In [ ]:
print(S)